// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PENTDRIVEApi.Data;

#nullable disable

namespace PENTDRIVEApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110214123_UpdateSenhaHashColumn")]
    partial class UpdateSenhaHashColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PENTDRIVEApi.Models.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ITEM");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("PRECO_UNI");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.Property<decimal>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("SUBTOTAL");

                    b.Property<int>("VendaId")
                        .HasColumnType("int")
                        .HasColumnName("ID_VENDA");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("itens_venda", (string)null);
                });

            modelBuilder.Entity("PENTDRIVEApi.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_MOVIMENTO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_HORA");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int?>("IdVenda")
                        .HasColumnType("int")
                        .HasColumnName("ID_VENDA");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto");

                    b.HasIndex("IdVenda");

                    b.ToTable("mov_estoque");
                });

            modelBuilder.Entity("PENTDRIVEApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUTO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("longtext")
                        .HasColumnName("COD_BARRAS");

                    b.Property<int>("Estoque")
                        .HasColumnType("int")
                        .HasColumnName("QNTD_ESTOQUE");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("PRECO_UNI");

                    b.HasKey("Id");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("PENTDRIVEApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NOME");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ROLE");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("VARBINARY(64)")
                        .HasColumnName("SENHA_HASH");

                    b.HasKey("Id");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("PENTDRIVEApi.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_VENDA");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CnpjCpf")
                        .HasColumnType("longtext")
                        .HasColumnName("CNPJ_CPF");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_HORA");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("longtext")
                        .HasColumnName("FORMA_PAG");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("VALOR_PAGO");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("VALOR_TOTAL");

                    b.HasKey("Id");

                    b.ToTable("venda", (string)null);
                });

            modelBuilder.Entity("PENTDRIVEApi.Models.ItemVenda", b =>
                {
                    b.HasOne("PENTDRIVEApi.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PENTDRIVEApi.Models.Venda", "Venda")
                        .WithMany("ItensVenda")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("PENTDRIVEApi.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("PENTDRIVEApi.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PENTDRIVEApi.Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("IdVenda");

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("PENTDRIVEApi.Models.Venda", b =>
                {
                    b.Navigation("ItensVenda");
                });
#pragma warning restore 612, 618
        }
    }
}
